### ISSUE TITLE
template based edits are always zero and way to increase sensitivity

### ISSUE THREAD

**Issue by npatel-ah** [nf-core/crisprseq#72]
### Description of feature

I have a few inquiries and a request that I would greatly appreciate your assistance with.

Following my analysis of several samples using the targeted pipeline (v.2.0.0), I noticed that upon reviewing the *_edits.csv files for all samples, the counts for template-based edits consistently read as 0. Could this possibly be attributed to the fact that I only provided reference sequences and omitted templates? 

Would you please  clarify on the distinction between reference and template sequences. Are they expected to differ, or can they be identical? 

We have observed a higher number of edits than initially anticipated. Is there a means by which the sensitivity of the pipeline can be adjusted to address this? Also the primer sequences should it retained within the reference/template sequences or removed.

I attempted to execute the pipeline using Singularity, but encountered an issue at the "SAMPLESHEET_CHECK" stage, resulting in a "command not found" error. Unfortunately, I do not have the precise log for this. However, when using Docker, no such issues arise.

Thanks in advance for your help.

**Comment by mirpedrol** [comment]
Hi @npatel-ah,

The template should be provided only for HDR experiments where you provide a DNA template to guide the edition. It is expected that template-base edits are 0 if a template is not provided for the analysis.
On the other hand, the reference is the origin DNA that you wish to edit.

Regarding the sensitivity, I am adding in the dev version more granular output plots and tables in order to allow a better filtering or edits. I hope this can improve your results.
We also have plans to include a normalization based on sequencing error.

Sequencing primers should not be included in the reference sequence.

I can't replicate your Singularity error, it would be useful if you would provide more information such as the `.nextflow.log` file or the commands you use to run the pipeline.

Thanks for your feedback!

**Comment by npatel-ah** [comment]
Hello, 
Thank you so much for all your comment and clarification. 

Also, appreciate your help with increasing sensitivity, I will give it try once it's available.  

I've re-run the test for singularity please see attached log.  It seems that the error is during the pull. 

[nextflow.log](https://github.com/nf-core/crisprseq/files/12397379/nextflow.log)
```


Pulling Singularity image https://depot.galaxyproject.org/singularity/python:3.8.3 [cache /home/nap39/singularity/depot.galaxyproject.org-singularity-python-3.8.3.img]
ERROR ~ Error executing process > 'NFCORE_CRISPRSEQ:CRISPRSEQ_TARGETED:INPUT_CHECK:SAMPLESHEET_CHECK'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name depot.galaxyproject.org-singularity-python-3.8.3.img.pulling.1692629198557 https://depot.galaxyproject.org/singularity/python:3.8.3 > /dev/null
  status : 255
  message:
    ERROR: pull is only supported for shub URIs

 -- Check '.nextflow.log' file for details

```

**Comment by npatel-ah** [comment]
I think i've found the issues with pull. It seems to be old version of singularity on our system.  
https://github.com/apptainer/singularity/issues/4548

After updating the singularity to the recent version, here is the error log. 

[nextflow_updated_singularity.log](https://github.com/nf-core/crisprseq/files/12397917/nextflow_updated_singularity.log)

**Comment by mirpedrol** [comment]
This could be a singularity problem, could you try to follow the instructions listed in the ["Cannot find input files when using Singularity"](https://nf-co.re/docs/usage/troubleshooting#cannot-find-input-files-when-using-singularity) section of nf-core troubleshooting?

**Comment by mirpedrol** [comment]
Closing this issue as it seems to be solved. Please re-open it if it's not
